# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-23 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='codigo_barras',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='codigo_topografico',
            field=models.CharField(max_length=50),
        ),
    ]
