# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.CharField(max_length=150),
        ),
    ]
