# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-01 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20160923_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesor',
            name='nombre_asesor',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='codigo_barras',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='codigo_topografico',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion_proyecto',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tematica',
            name='nombre_tematica',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='tiposolucion',
            name='nombre_tipo_solucion',
            field=models.CharField(max_length=80),
        ),
    ]
