# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-11 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20161009_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iniciomodel',
            name='imagen_presentacion',
        ),
    ]
