# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20160909_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tipo_tematica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Tematica'),
            preserve_default=False,
        ),
    ]
