# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20160909_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorproyecto',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nombre_autor',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AutorProyecto',
        ),
    ]
